channel_names = [
    "finance", "crypto", "trading", "startup", "investor", "blockchain", "forex", "stocks", "bitcoin", "business",
    "economy", "venture", "banking", "analytics", "marketing", "branding", "strategy", "insights", "wealth", "success",
    "capital", "growth", "profits", "revenue", "passive", "moneyflow", "trends", "financial", "valuation", "funding", "leadership",
    "fintech", "entrepreneur", "management", "innovation", "technology", "software", "hardware", "networking", "cybersecurity", "cloud",
    "programming", "development", "startups", "ecommerce", "automation", "artificial", "machinelearning", "robotics", "biotech", "pharma",
    "healthcare", "medicine", "nutrition", "wellness", "fitness", "lifestyle", "coaching", "selfgrowth", "psychology", "mindset",
    "inspiration", "motivation", "successmind", "personaldevelopment", "happiness", "creativity", "writing", "content", "copywriting", "brandingstrategy",
    "advertising", "media", "socialmedia", "youtube", "instagram", "tiktok", "twitter", "linkedin", "growthhacking", "seo",
    "digitalmarketing", "affiliate", "dropshipping", "onlinestore", "webdesign", "uxdesign", "productdesign", "gamedev", "gameindustry", "gamingnews",
    "mobileapps", "iosdev", "androiddev", "webdevelopment", "fullstack", "backend", "frontend", "cloudcomputing", "saas", "datascience",
    "bigdata", "aiethics", "deeplearning", "iotdevices", "smarttech", "augmentedreality", "virtualreality", "metaverse", "web3", "nftmarket",
    "cryptoassets", "altcoins", "defi", "smartcontracts", "dapps", "staking", "miningcrypto", "bitcoinnews", "cryptotrends", "tradingstrategies",
    "daytrading", "swingtrading", "technicalanalysis", "fundamentalanalysis", "stockmarket", "wallstreet", "hedgefunds", "etftrading", "realestate", "propertyinvestment",
    "luxuryliving", "highendrealty", "architecture", "interiordesign", "homedecor", "landscaping", "construction", "urbanplanning", "smartcities", "greentech",
    "renewableenergy", "solarenergy", "windpower", "hydropower", "cleantech", "sustainable", "climatechange", "ecofriendly", "carbonneutral", "zerowaste",
    "ethicalbusiness", "socialimpact", "csr", "impactinvesting", "biodiversity", "organicfarming", "permaculture", "veganlife", "plantbased", "holistichealth",
    "mindfulness", "meditation", "spirituality", "selfcare", "mentalhealth", "therapy", "coachinglife", "yoga", "pilates", "athomeworkout",
    "crossfit", "bodybuilding", "calisthenics", "nutritiontips", "weightloss", "healthyhabits", "biohacking", "longevity", "alternativehealth", "naturalremedies",
    "homesteading", "survival", "prepping", "bushcraft", "camping", "outdoors", "hiking", "backpacking", "mountaineering", "adventuretravel",
    "offgrid", "selfsufficiency", "tinyhomes", "vanlife", "rvliving", "minimalism", "simpleliving", "decluttering", "financialfreedom", "firemovement",
    "sidehustles", "remotejobs", "freelancing", "digitalnomad", "workfromhome", "solopreneur", "gigwork", "passiveincome", "onlinebusiness", "marketinghacks",
    "negotiation", "sales", "publicspeaking", "storytelling", "presentation", "selfbranding", "networkingpro", "careerchange", "jobhunting", "resumehacks",
    "interviewtips", "productivity", "timemanagement", "focushacks", "habitbuilding", "goalsetting", "motivationdaily", "journaling", "selfawareness", "positivity",
    "highperformance", "mentalclarity", "emotionalintelligence", "relationshipadvice", "parentingtips", "childdevelopment", "education", "learninghacks", "speedreading", "memorytraining",
    "brainpower", "intellectualgrowth", "bookclub", "philosophy", "history", "psychologyinsights", "sociology", "politicalscience", "economics", "futuretrends",
    "globalnews", "geopolitics", "worldevents", "spaceexploration", "astronomy", "astrophysics", "quantumphysics", "scientificbreakthroughs", "medicaldiscoveries", "genetics",
    "biotechnology", "nanotechnology", "chemistry", "engineering", "roboticsfuture", "aiinnovation", "3dprinting", "blockchaintech", "opensource", "ethicalhacking",
    "cyberawareness", "digitalprivacy", "cybercrime", "forensics", "encryption", "internetsecurity", "vpnsecurity", "opensourceprojects", "linuxcommunity", "codingbootcamp",
    "hackathon", "startuplife", "venturecapital", "angelinvesting", "businesshacks", "leadershiptips", "corporatestrategy", "executivementor", "growthstrategy", "highperformancehabits",
    "teamwork", "managementskills", "hrstrategy", "workplacetrends", "futureofwork", "remoteworking", "distributedteams", "automationfuture", "robotrevolution", "aipowered",
    "datastrategy", "datagovernance", "dataprivacy", "datasciencejobs", "mlops", "aiops", "quantfinance", "algorithmictrading", "highfrequencytrading", "marketanalysis",
    "trendforecasting", "cryptoeconomy", "tokenomics", "nftart", "nftgaming", "metaversebusiness", "virtualrealestate", "gamedevelopment", "esports", "streaming",
    "contentcreation", "influencermarketing", "brandgrowth", "personalbrand", "creatoreconomy", "patreon", "substack", "onlinenews", "independentjournalism", "crowdfunding",
    "charityprojects", "philanthropy", "socialgood", "nonprofit", "communitybuilding", "impactleaders", "changemakers", "futureleaders", "youthleadership", "educationreform"
]